### ISSUE TITLE
Replace the raw_objc functions call on `manual_cfront` branch.

### ISSUE THREAD

**Issue by crlf0710** [crlf0710/tectonic#101]
There're some objc code that i don't fully understand, it would be great if someone who knows objc better can help replace them.

Note that that branch doesn't build yet because of the several missing functions. Still slowly replacing them with rust...

**Comment by cormacrelf** [comment]
I’ve never heard of `raw_objc` in my life. Do you intend it as a placeholder for actual Objective-C message sending? Because https://docs.rs/objc

**Comment by crlf0710** [comment]
Yes, there's some objc syntax in the original .mm file, which c2rust doesn't support. I replaced them with a fake function and named it `raw_objc`, leaving the objc syntax within string as is.

**Comment by cormacrelf** [comment]
I'm having a go

**Comment by crlf0710** [comment]
Done in #104
