### ISSUE TITLE
FIXME regarding libpng-sys/libz-sys

### ISSUE THREAD

**Issue by chirsz-ever** [crlf0710/tectonic#155]
How could this FIXME be explained?
https://github.com/crlf0710/tectonic/blob/957fad292b2bdb0ec0f8472009ee8954f35ec21c/dpx/src/dpx_pdfobj.rs#L2229-L2238

**Comment by mulimoen** [comment]
`libpng-sys` does not take null-pointer allocation and free, when they should. If given null, they should use the system allocator. Seems no upstream issue was raised for this

**Comment by mulimoen** [comment]
FIXME is wrong in which library it is, it should be `libz-sys`. Issue was raised in https://github.com/rust-lang/libz-sys/issues/55

**Comment by mulimoen** [comment]
`libz-sys` is rather ugly to fix with a patch, as it links to a system library and has several dependencies which must be patched at the same time.

See also
https://github.com/rust-lang/rust/issues/8730

**Comment by crlf0710** [comment]
Yes, that would be a breaking change for that crate... Currently we are using `std::mem::zeroed()` as the workaround so it's not an urgent issue. But the warning is indeed annoying though.

**Comment by crlf0710** [comment]
The current hack will soon become a panic after https://github.com/rust-lang/rust/pull/66059 lands. Currently it's running a crater run.

**Comment by cormacrelf** [comment]
Generally the flate2 crate solves this by implementing zalloc/zfree using std::alloc, and i already switched to it in #176. I’ll have a proper go at splitting that into something that passes.
