### ISSUE TITLE
Review code translated from `do {} while expr` with `continue` statements

### ISSUE THREAD

**Issue by cormacrelf** [crlf0710/tectonic#166]
In `do {} while expr` blocks in C, `continue` means "jump to the end of the `{}` block. Ultimately this means the `expr` check is done before entering the loop again. Any C code that has been manually rewritten as `loop { if X { continue; } if Y { break } }` might be worth checking, because `continue` does not check Y and may cause infinite looping. Most of these instances are probably still using `match current_block`.

_Originally posted by @burrbull in https://github.com/crlf0710/tectonic/pull/159_

**Comment by chirsz-ever** [comment]
After checking the `continue` of the original C code ([Search Result](https://github.com/tectonic-typesetting/tectonic/search?q=continue&unscoped_q=continue)), I found there are just 2 do-while block having `continue`:
- [flat_table of dpx-pdfname.c](https://github.com/tectonic-typesetting/tectonic/blob/2210ff2214d25835064c042d90a84fd3ced8eed4/tectonic/dpx-pdfnames.c#L368) which was aware of with tests in #159.
- [build_page of xetex-pagebuilder.c](https://github.com/tectonic-typesetting/tectonic/blob/c9ed3ec91a020e54a4f51ba7e69962ec9c4a7d62/tectonic/xetex-pagebuilder.c#L505)

So we must pay attention when rewriting `build_page` of `engine/src/xetex_pagebuilder.rs`

**Comment by cormacrelf** [comment]
pagebuilder reminds me -- https://github.com/crlf0710/tectonic/blob/187ed7b79cabbe4fcb14ca9a9942b6e037290f44/engine/src/xetex_pagebuilder.rs#L56-L83

Those ridiculous macro expansions (I presume) need to go. A nice multiline regex would catch most I'd imagine. Maybe a struct definition for eqtb, etc, eventually.

**Comment by mulimoen** [comment]
You can find the macro translations in xetex0
