### ISSUE TITLE
broken windows build

### ISSUE THREAD

**Issue by burrbull** [crlf0710/tectonic#246]
@crlf0710

**Comment by crlf0710** [comment]
That's strange... The error seems come from https://github.com/mcgoo/vcpkg-rs/blob/b8c887f396bbe0fd9ed41ca22621ce85f53dde0a/vcpkg/src/lib.rs#L1032 
But i can't see why `TARGET` environment variable isn't set as expected.

Will look into this.

**Comment by crlf0710** [comment]
Cannot reproduce locally. Maybe something wrong on travis settings? Will create a branch and let travis run.

**Comment by crlf0710** [comment]
https://travis-ci.com/crlf0710/tectonic/jobs/270401492#L1813
So travis CI somehow uses `-gnu` target now, while we're requiring `-msvc` target.
