### ISSUE TITLE
Run C2Rust on xetex-macos.c

### ISSUE THREAD

**Issue by crlf0710** [crlf0710/tectonic#25]
I don't have a mac machine, and i think we need a volunteer on this.

**Comment by lovasoa** [comment]
How would this be done ?

**Comment by crlf0710** [comment]
1. Install c2rust per the instructions here, you'll need the specified nightly toolchain it told you:
https://github.com/immunant/c2rust
2. Use the `intercept-build` tool to compile the xetex-macos.c.
https://github.com/immunant/c2rust#-with-intercept-build
A `compile_commands.json` will be generated.
3. run `c2rust transpile compile_commands.json` and Pull Request the xetex-macos.rs you got~
Done~~

**Comment by cormacrelf** [comment]
A bit of remaining work but it successfully compiles and produces a PDF on my mac @ 10.14.

Eventually `xetex_macos.rs` should probably use the bindings from https://docs.rs/core-foundation instead of `extern`s, but that's for another day.

**Comment by crlf0710** [comment]
Great. I'll try to fix the unittests and clean up the changes in xetex_ext.rs

**Comment by cormacrelf** [comment]
(Closed.)
