### ISSUE TITLE
tectonic-on-arxiv doesn't autostart on oxidize branch

### ISSUE THREAD

**Issue by burrbull** [crlf0710/tectonic#287]
cc @Mrmaxmeier

**Comment by Mrmaxmeier** [comment]
Sorry about that. Should be fixed now.
(cc: https://github.com/tectonic-typesetting/tectonic/pull/666)

**Comment by burrbull** [comment]
Now it's queued all time.

**Comment by Mrmaxmeier** [comment]
https://github.com/Mrmaxmeier/tectonic-on-arXiv/commit/732158a404b935d5562c9f2f9d1c330c781c90d1
That was Nodejs being Nodejs where queues randomly get stuck if you're using a transpiler that targets old versions of JS .__.
Let me know if there's any more issues :slightly_smiling_face:

**Comment by burrbull** [comment]
No change.
https://github.com/crlf0710/tectonic/pull/288/checks?check_run_id=1320509671

**Comment by Mrmaxmeier** [comment]
This check run should start in about 5 minutes. The bot is currently testing the base commit to be able to compare outputs for the PR commit.

**Comment by burrbull** [comment]
It would be great to see queue on the site.
