### ISSUE TITLE
Build fails on macos

### ISSUE THREAD

**Issue by lovasoa** [crlf0710/tectonic#4]
Here are the files I had to add in order to compile under macos:

```
        xetex-constants.h
        xetex-io.h
        xetex-stringpool.h
        xetex-xetexd.h
```

Maybe MacOS could be added as a CI test target ?

**Comment by crlf0710** [comment]
Added those files at https://github.com/crlf0710/tectonic/commit/d11db29906a48c04abe32bd3dbff2c19c977058f

Let me see how to enable travis...

**Comment by lovasoa** [comment]
Thank you, it compiles on my computer after your commit.

**Comment by crlf0710** [comment]
Made some new progress. Still have a few linking errors.

**Comment by crlf0710** [comment]
Now the unit tests pass. Closing~

**Comment by lovasoa** [comment]
If everything works, then it may be worth enforcing build success on MacOS in travis, in order to avoid future regressions:

https://github.com/crlf0710/tectonic/blob/oxidize/.travis.yml#L21-L22
