### ISSUE TITLE
Replace libpng calls with libpng-sys crate.

### ISSUE THREAD

**Issue by crlf0710** [crlf0710/tectonic#7]

**Comment by ThomasdenH** [comment]
The recommendation in the readme is to use a Rust PNG library instead, is that a better idea?

**Comment by crlf0710** [comment]
That will need a lot more code changes because of API difference, so i think we can just use libpng-sys first. And when all the unit testing stuff is working on all platforms, we then try to switch to a Rust PNG library.

**Comment by ThomasdenH** [comment]
Ok. I'll go for this then. I think it's just the file `dpx_pngimage.rs`?

**Comment by crlf0710** [comment]
Yes, i think so.

**Comment by crlf0710** [comment]
Done in #18
