### ISSUE TITLE
Rustify DVI opcodes

### ISSUE THREAD

**Issue by cormacrelf** [crlf0710/tectonic#74]
- [ ] Should it be a `#[repr(u8)]` enum? Apparently opcodes can be multibyte.
- [ ] fn(u8) -> Option<DviOpcode> (maybe use https://crates.io/crates/enum-primitive-derive)

They're all over dpx_dvi.rs and elsewhere as literals like `128`.

**Comment by chirsz-ever** [comment]
In my opinion, it should not use `enum` here, because the opcodes' value are not arbitrary, they are specialized by DVI standard. In other words, their value precede their names. Using `enum` may cause confusing. `enum` are usually used for something whose name precede their value in memory.

**Comment by cormacrelf** [comment]
Not really, it's very common to have custom discriminants. I don't think it really matters here, given that we don't need compile-time-checked exhaustive matching (I presume).

```rust
#[repr(u8)]
enum Something {
    Every = 1,
    Variant = 2,
    Has = 3,
    A = 4,
    Value = 5,
}
```
