### ISSUE TITLE
warn and info should print to given handle

### ISSUE THREAD

**Issue by mulimoen** [crlf0710/tectonic#82]
Noticed a regression where something was printed even when setting "--chatter minimal". [1]

Git bisect shows commit 0b290a7d as the culprit. The macros info! and warn! should print to the given handle, and not stdout.

[1] test program
`\documentclass{article}\begin{document}h\end{document}`

**Comment by burrbull** [comment]
Can you replace `info!` with:
```rust
#[macro_export]
macro_rules! info(
    ($($arg:tt)*) => {
        if !(unsafe{crate::dpx_error::_dpx_quietness} > 0) {
            let s = format!($($arg)*);
            let cs = std::ffi::CString::new(s.as_str()).unwrap();
            let n = cs.to_bytes().len();
            unsafe {
                let raw = cs.into_raw();
                tectonic_bridge::ttstub_output_write(
                    crate::dpx_error::_dpx_ensure_output_handle(),
                    raw,
                    n as u64,
                );
                let _ = std::ffi::CString::from_raw(raw);
            }
            unsafe{crate::dpx_error::_last_message_type = crate::dpx_error::DPX_MESG_INFO;}
        }
    };
);
```
and make public
```rust
pub unsafe extern "C" fn _dpx_ensure_output_handle() -> rust_output_handle_t {
```

and say does this fix problem with `info!`?

**Comment by mulimoen** [comment]
Could we implement this through the Write trait on the handle? It feels a bit wasteful to always pad the output with the trailing zero

**Comment by burrbull** [comment]
As far as I understand we need to rewrite `bridge` `ttstub` system for that.
