### ISSUE TITLE
Replace setjmp/longjmp with catch_panic

### ISSUE THREAD

**Issue by crlf0710** [crlf0710/tectonic#9]
The c code uses setjmp/longjmp in several places. They're not expressible in current rust. So we want to change it to using panic! and catch_panic.

**Comment by burrbull** [comment]
#16

**Comment by chirsz-ever** [comment]
Do you mean `std::panic::catch_unwind`? I found that even you wrap the `panic` code with `catch_unwind`, it will still output panic infomations to stderr ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e9a1c8cbd38a445658170e94382c8348)).
Maybe it needs another idea to remove `setjmp` and `longjmp`.

**Comment by ThomasdenH** [comment]
Most of the error propagation that currently returns `i32` can probably be replaced with `Result`. Not sure it that can simply be extended to `longjump` and `setjump`?

**Comment by crlf0710** [comment]
@chirsz-ever the backtrace is output by the default panic hook. So this is actually customizable.
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=79d2e4cadbd5072c396c206faf5e08ee).

**Comment by crlf0710** [comment]
@ThomasdenH Yup, there definitely needs more `Result`s, but the ones currently using `setjmp/longjmp` are the job aborting scenarios. So maybe it's not worth it to add so many processing routes...

**Comment by burrbull** [comment]
Can `_tt_abort` be replaced with `panic!`?

**Comment by crlf0710** [comment]
I think so!
